apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: docker.io/hekai/gcr.io_heptio-images_ks-guestbook-demo_0.2:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
